### PR TITLE
Adopt examples with the new changes and improve the build script

### PR DESCRIPTION
**Pull request by ebraminio**

### CODE REVIEW

**Comment by ebraminio** [comment]
Also are you interested on hiding aubio's own symbols? That could be done with the following patch however I am not applying it as I guessed having them around would be fun somehow but it decreases output size couple of bytes (~30 bytes IIRC)

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2f6b4eb..351156f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -27,10 +27,7 @@ set(source_files
   ${PROJECT_SOURCE_DIR}/aubio/src/cvec.c
   ${PROJECT_SOURCE_DIR}/aubio/src/fvec.c
   ${PROJECT_SOURCE_DIR}/aubio/src/lvec.c
-  ${PROJECT_SOURCE_DIR}/aubio/src/mathutils.c
-  ${PROJECT_SOURCE_DIR}/src/fft.cc
-  ${PROJECT_SOURCE_DIR}/src/tempo.cc
-  ${PROJECT_SOURCE_DIR}/src/pitch.cc)
+  ${PROJECT_SOURCE_DIR}/aubio/src/mathutils.c)
 
 add_definitions(-DHAVE_CONFIG_H)
 set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-rtti -DEMSCRIPTEN_HAS_UNBOUND_TYPE_NAMES=0 -fno-exceptions -Oz -s EXPORTED_RUNTIME_METHODS=[] -s MODULARIZE=1 --memory-init-file 0 --closure 1 --llvm-lto 1 --bind -s WASM=1")
@@ -38,10 +35,16 @@ set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-rtti -DEMSCRIPTEN_HAS_UNBOUND_TYPE_
 include_directories(src)
 include_directories(aubio/src)
 
-add_executable(aubio ${source_files})
+add_library(aubio ${source_files})
+add_executable(aubiojs
+  ${PROJECT_SOURCE_DIR}/src/fft.cc
+  ${PROJECT_SOURCE_DIR}/src/tempo.cc
+  ${PROJECT_SOURCE_DIR}/src/pitch.cc)
+target_link_libraries(aubiojs aubio)
+
 
 # copy results to examples/
-add_custom_command(TARGET aubio POST_BUILD
+add_custom_command(TARGET aubiojs POST_BUILD
   COMMAND ${CMAKE_COMMAND} -E copy
-    ${CMAKE_BINARY_DIR}/aubio.js ${CMAKE_BINARY_DIR}/aubio.wasm
+    ${CMAKE_BINARY_DIR}/aubiojs.js ${CMAKE_BINARY_DIR}/aubiojs.wasm
     ${CMAKE_SOURCE_DIR}/examples/)
\ No newline at end of file
```

**Comment by qiuxiang** [comment]
Thanks a lot for these changes. I need some time to check it. :smiley:

**Comment by ebraminio** [comment]
No problem, please note that the compile command is also changed, and you should use `emcmake cmake -Bbuild -H. -GNinja && ninja -Cbuild` so no longer manual emscripten compiler location hardcoding. If you don't like Ninja, you can remove `-GNinja` so the build step will be turned into `make -Cbuild` or you can turn it into make system agnostic build with `cmake --build build`. Let me know which one and anything else you prefer more.

All the equivalent combinations:

Ninja:
`emcmake cmake -Bbuild -H. -GNinja && ninja -Cbuild` (currently)
`emcmake cmake -Bbuild -H. -GNinja && cmake --build build`

Make:
`emcmake cmake -Bbuild -H. && make -Cbuild` (similar to previous)
`emcmake cmake -Bbuild -H. && cmake --build build`

**Comment by qiuxiang** [comment]
Your improvements to the build script are great. But I think ninja is optional. We should provide the simplest compile command in README.

After that, I consider making an npm package to make this library easier to use, and write some tests.

**Comment by ebraminio** [comment]
Thank you very much! Definitely, Ninja is optional and just feels better :) Adding npm module is easy, it starts with adding a package.json like [this](https://github.com/ebraminio/pad.js/blob/master/package.json) and an upload command like `npm version 0.0.1 && git commit -am "0.0.1" && git push --follow-tags && npm publish` (or `npm version {patch|minor|major}`, but don't know about WASM support on Node.js yet.

**Comment by qiuxiang** [comment]
Exactly, making npm package is easy. The problem is supporting both nodejs and browser.

**Comment by ebraminio** [comment]
`node -e "require('./aubio.js')().then(m => console.log(m.AubioFFT))"`

Hmm it seems it is working at least on v9.4.0 that I am testing, didn't do an actual test yet however.

**Pull request merged**
